<?php      
class FAjax {
   const TYPE_METHOD_CONTENT_REPLACE_NONE = 'TYPE_METHOD_CONTENT_REPLACE_NONE';
   const TYPE_METHOD_CONTENT_REPLACE = 'TYPE_METHOD_CONTENT_REPLACE';
   const TYPE_METHOD_CONTENT_APPEND_ABOVE = 'TYPE_METHOD_CONTENT_APPEND_ABOVE';
   const TYPE_METHOD_CONTENT_APPEND_BELOW = 'TYPE_METHOD_CONTENT_APPEND_BELOW';
   const TYPE_METHOD_CONTENT_REPLACE_ALL = 'TYPE_METHOD_CONTENT_REPLACE_ALL';
   
   const TYPE_METHOD_CONTENT_DECORATION_NONE = 'TYPE_METHOD_CONTENT_DECORATION_NONE';
   const TYPE_METHOD_CONTENT_DECORATION_FADE = 'TYPE_METHOD_CONTENT_DECORATION_FADE';
   const TYPE_METHOD_CONTENT_DECORATION_ROLL = 'TYPE_METHOD_CONTENT_DECORATION_ROLL';
   
   const STATUS_RESPONSE_NO_REPLACE_NO_AFTERACTION_NO_AFTERACTION_ALTERNATIVE = '<div id="aj:no_replace_no_afteraction_no_afteraction_alternative" />';
   const STATUS_RESPONSE_NO_REPLACE_NO_AFTERACTION_YES_AFTERACTION_ALTERNATIVE = '<div id="aj:no_replace_no_afteraction_yes_afteraction_alternative" />';
   const STATUS_RESPONSE_YES_REPLACE_NO_AFTERACTION = '<div id="aj:yes_replace_no_afteraction" />';
   const STATUS_RESPONSE_NO_REPLACE_YES_AFTERACTION = '<div id="aj:no_replace_yes_afteraction" />';
   const STATUS_RESPONSE_YES_REPLACE_YES_AFTERACTION = '<div id="aj:yes_replace_yes_afteraction" />';
   
   const TYPE_METHOD_ANIMATION_CHANGE_ALL_ELEMENTS = 'TYPE_METHOD_ANIMATION_CHANGE_ALL_ELEMENTS';
   const TYPE_METHOD_ANIMATION_CHANGE_SELECTED_ELEMENTS = 'TYPE_METHOD_ANIMATION_CHANGE_SELECTED_ELEMENTS';
   const TYPE_METHOD_ANIMATION_CHANGE_OTHER_ELEMENTS = 'TYPE_METHOD_ANIMATION_CHANGE_OTHER_ELEMENTS';
}
?>