<?php      
class FModulePlantMonitoringManagement {
   const TYPE_QUESTION_FIELD_NUMERIC = 'NUMERIC';
   const TYPE_QUESTION_FIELD_ALFANUMERIC = 'ALFANUMERIC';
   const TYPE_QUESTION_FIELD_BIT = 'BIT';
   
   const TYPE_QUESTION_REPEAT_DIALY = 'DIALY';
   const TYPE_QUESTION_REPEAT_WEEKLY = 'WEEKLY';
   const TYPE_QUESTION_REPEAT_MONTHLY = 'MONTHLY';
   
   const HEADER_MAIN_COLOR = 'EEEEEE';
   const HEADER_GROUP_FORM_COLOR = 'FFEDED';
   const HEADER_FORM_COLOR = 'EFEEE0';
}
?>